# Generated by Django 3.1.1 on 2020-09-08 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Reward Name')),
                ('min_amount', models.DecimalField(decimal_places=2, default='', max_digits=8, verbose_name='Minimum Amount')),
                ('desc', models.CharField(default='', max_length=255, verbose_name='Reward Description')),
                ('short_desc', models.CharField(default='', max_length=255, verbose_name='Short Reward Description')),
                ('fine_print', models.CharField(blank=True, default='', max_length=255, verbose_name='Fine Print')),
                ('icon_class', models.CharField(blank=True, default='', max_length=255, verbose_name='Icon Classes')),
                ('img', models.URLField(blank=True, default='', verbose_name='Image URL')),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255, verbose_name='Author Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Author Email')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=7, verbose_name='Currency Abbreviation')),
                ('value', models.FloatField(verbose_name='USD to currency')),
                ('update', models.BooleanField(verbose_name='Update value from API?')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('text', models.TextField()),
                ('notify', models.BooleanField(default=True, verbose_name='Notify me on replies')),
                ('team_response', models.BooleanField(default=False, verbose_name='Add the Team Response flag')),
                ('orig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='crowdfunding.question', verbose_name='In reply to')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=255, verbose_name='Name')),
                ('addr1', models.CharField(default='', max_length=255, verbose_name='Address 1')),
                ('addr2', models.CharField(blank=True, default='', max_length=255, verbose_name='Address 2')),
                ('city', models.CharField(default='', max_length=255, verbose_name='City')),
                ('state', models.CharField(default='', max_length=255, verbose_name='State/Province')),
                ('pcode', models.CharField(default='', max_length=255, verbose_name='Postal Code')),
                ('country', models.CharField(default='', max_length=255, verbose_name='Country')),
                ('amount', models.DecimalField(decimal_places=2, default='', max_digits=8, verbose_name='Amount')),
                ('ptype', models.CharField(choices=[('CC', 'Credit Card'), ('BC', 'Bitcoin'), ('PP', 'PayPal'), ('BT', 'Bank Transfer')], max_length=2, verbose_name='Payment Type')),
                ('pref', models.CharField(blank=True, default='', max_length=255, verbose_name='Payment Reference')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('notify', models.BooleanField(verbose_name='Notify me if the project team posts an update?')),
                ('namecredit', models.CharField(blank=True, default='', max_length=255, verbose_name='Credit Name')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='Notes')),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='crowdfunding.reward', verbose_name='Reward Level')),
            ],
        ),
    ]
