# Generated by Django 3.1.1 on 2020-09-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='orig',
        ),
        migrations.DeleteModel(
            name='Update',
        ),
        migrations.DeleteModel(
            name='Value',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='fine_print',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='icon_class',
        ),
        migrations.AlterField(
            model_name='order',
            name='addr1',
            field=models.CharField(max_length=255, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='order',
            name='addr2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(max_length=255, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='namecredit',
            field=models.CharField(blank=True, max_length=255, verbose_name='Credit Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.CharField(blank=True, max_length=255, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pcode',
            field=models.CharField(max_length=255, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pref',
            field=models.CharField(blank=True, max_length=255, verbose_name='Payment Reference'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ptype',
            field=models.CharField(choices=[('CC', 'Credit Card'), ('BT', 'Bank Transfer')], max_length=2, verbose_name='Payment Type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(max_length=255, verbose_name='State/Province'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='desc',
            field=models.CharField(max_length=255, verbose_name='Reward Description'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='img',
            field=models.URLField(blank=True, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Minimum Amount'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Reward Name'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='short_desc',
            field=models.CharField(max_length=255, verbose_name='Short Reward Description'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
